version: 2.1

orbs:
  cypress: cypress-io/cypress@1.26.0

jobs:
  checkout:
    docker:
      - image: circleci/node:15.14.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
            - .cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  commitlint:
    docker:
      - image: circleci/node:15.14.0
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Lint relevant commit messages
          command: npm run commitlint:ci

  unit-test-contracts:
    docker:
      - image: circleci/node:15.14.0
      - image: trufflesuite/ganache-cli:v6.10.1
        command: ganache-cli -e 100000000000 -l 6700000 -p 7545
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Test solidity contracts
          command: npm run test:contracts

  build-frontend:
    docker:
      - image: circleci/node:15.14.0
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build Frontend
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  release:
    docker:
      - image: circleci/node:15.14.0
    steps:
      - attach_workspace:
          at: ~/project
      - run: npx semantic-release

workflows:
  build:
    jobs:
      - checkout
      - commitlint:
          requires:
            - checkout
      - unit-test-contracts:
          requires:
            - checkout
      - cypress/install:
          requires:
            - checkout
      - cypress/run:
          start: npm start
          wait-on: "http://localhost:1234"
          requires:
            - cypress/install
          attach-workspace: true
      - build-frontend:
          requires:
            - checkout
      - release:
          context: michaelhettmer
          requires:
            - commitlint
            - build-frontend
            - unit-test-contracts
            - cypress/run
          filters:
            branches:
              only: master
